package rimbreaker.backend.payload.response;

import rimbreaker.backend.entity.Standings;

public class ResponseStandingsConTeam {
    private Standings standings;
    private String teamName;

    // Default constructor
    public ResponseStandingsConTeam() {
    }

    // Constructor with required parameters
    public ResponseStandingsConTeam(Standings standings, String teamName) {
        this.standings = standings;
        this.teamName = teamName;
    }

    // Getters and setters (generated by Lombok or manually)
    public Standings getStandings() {
        return standings;
    }

    public void setStandings(Standings standings) {
        this.standings = standings;
    }

    public String getTeamName() {
        return teamName;
    }

    public void setTeamName(String teamName) {
        this.teamName = teamName;
    }
}
