version: '3.8'
services:
  web:
    image: php:7.4-apache
    ports:
      - 80:80
    volumes:
      - ./html:/var/www/html
    depends_on:
      - db

  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: rimbreaker
      MYSQL_USER: backend
      MYSQL_PASSWORD: 
    volumes:
      - ./mysql:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - 8080:80
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: root

  ubuntu:
    image: ubuntu:22.04

